"""
API routes for PageIndex tree index data.

Provides endpoints for the frontend to retrieve tree structures (mind maps)
generated by PageIndex during document processing.
"""

from fastapi import APIRouter, Depends, HTTPException
from lightrag import LightRAG
from lightrag.api.utils_api import get_combined_auth_dependency
from lightrag.tree_index import TreeIndexStorage


def create_tree_routes(
    rag: LightRAG,
    api_key: str | None = None,
) -> APIRouter:
    """Create the tree index router.

    Args:
        rag: The LightRAG instance (or proxy).
        api_key: Optional API key for auth.

    Returns:
        An ``APIRouter`` instance with tree index endpoints.
    """
    router = APIRouter(prefix="/tree", tags=["tree"])
    auth = get_combined_auth_dependency(api_key)

    def _get_storage() -> TreeIndexStorage | None:
        """Get the current TreeIndexStorage from the RAG instance."""
        current = rag
        # Unwrap proxy if needed
        if hasattr(rag, "_current"):
            current = rag._current()
        return getattr(current, "tree_index", None)

    @router.get("/list")
    async def list_trees(_=Depends(auth)):
        """List all documents that have a tree index.

        If processed documents exist without a tree index, automatically
        builds one from their text content in ``full_docs`` (lazy fallback
        so previously-uploaded documents appear without re-upload).
        """
        store = _get_storage()
        if store is None:
            return {"trees": [], "enabled": False}

        trees = store.list_trees()
        existing_ids = {t.get("doc_id", t.get("id")) for t in trees if isinstance(t, dict)}

        # Lazy-build missing trees from full_docs KV storage
        store_dir = getattr(store, "_dir", None)
        if store_dir is not None:
            kv_path = str(store_dir.parent / "kv_store_full_docs.json")
            import os as _os

            if _os.path.isfile(kv_path):
                from lightrag.tree_index import build_tree_from_text
                import json as _json

                try:
                    with open(kv_path, "r", encoding="utf-8") as _f:
                        all_data = _json.load(_f)
                    for doc_id, content_data in all_data.items():
                        if not doc_id or doc_id in existing_ids:
                            continue
                        if not isinstance(content_data, dict):
                            continue
                        text = content_data.get("content", "")
                        if not text.strip():
                            continue
                        try:
                            tree = build_tree_from_text(
                                text, doc_id, doc_name=doc_id
                            )
                            if tree:
                                store.save_tree(doc_id, tree, title=doc_id)
                                existing_ids.add(doc_id)
                        except Exception:
                            pass
                except Exception:
                    pass

        return {"trees": store.list_trees(), "enabled": True}

    @router.get("/{doc_id}")
    async def get_tree(doc_id: str, _=Depends(auth)):
        """Get the tree structure for a specific document."""
        store = _get_storage()
        if store is None:
            raise HTTPException(status_code=404, detail="Tree index not enabled")
        tree = store.get_tree(doc_id)
        if tree is None:
            raise HTTPException(status_code=404, detail="Tree not found")
        return tree

    @router.post("/rebuild")
    async def rebuild_trees(_=Depends(auth)):
        """Rebuild tree indexes for all processed documents that lack one."""
        store = _get_storage()
        if store is None:
            raise HTTPException(status_code=404, detail="Tree index not enabled")
        current = rag
        if hasattr(rag, "_current"):
            current = rag._current()

        if not hasattr(current, "full_docs"):
            return {"status": "ok", "rebuilt": 0, "errors": 0, "message": "full_docs not available"}

        from lightrag.tree_index import build_tree_from_text
        import asyncio

        existing = set(store._meta.keys()) if hasattr(store, "_meta") else set()
        built = 0
        errors = 0

        # Iterate full_docs to find processed documents without trees
        try:
            all_docs = await current.full_docs.get_by_id("__all__") if hasattr(current.full_docs, "get_by_id") else None
        except Exception:
            all_docs = None

        doc_ids_to_check: list[str] = []
        if isinstance(all_docs, list):
            for entry in all_docs:
                doc_id = None
                if isinstance(entry, dict):
                    doc_id = entry.get("_id") or entry.get("id")
                elif isinstance(entry, str):
                    doc_id = entry
                if doc_id and doc_id not in existing:
                    doc_ids_to_check.append(doc_id)
        elif isinstance(all_docs, dict):
            for doc_id in all_docs:
                if doc_id not in existing:
                    doc_ids_to_check.append(doc_id)

        # Also try doc_status for docs not in full_docs
        if not doc_ids_to_check:
            try:
                status_docs = await current.doc_status.get_by_ids([])
                if isinstance(status_docs, dict):
                    for doc_id in status_docs:
                        if doc_id not in existing:
                            doc_ids_to_check.append(doc_id)
            except Exception:
                pass

        for doc_id in doc_ids_to_check:
            try:
                content_data = await current.full_docs.get_by_id(doc_id)
                if not content_data:
                    continue
                text = (content_data.get("content") or "") if isinstance(content_data, dict) else ""
                if not text.strip():
                    continue
                tree = build_tree_from_text(text, doc_id, doc_name=doc_id)
                if tree:
                    store.save_tree(doc_id, tree, title=doc_id)
                    built += 1
            except Exception as e:
                errors += 1

        return {
            "status": "ok",
            "rebuilt": built,
            "errors": errors,
            "message": f"Built {built} tree(s), {errors} error(s). Existing trees before: {len(existing)}."
        }

    @router.delete("/{doc_id}")
    async def delete_tree(doc_id: str, _=Depends(auth)):
        """Delete the tree structure for a document."""
        store = _get_storage()
        if store is None:
            raise HTTPException(status_code=404, detail="Tree index not enabled")
        store.delete_tree(doc_id)
        return {"status": "ok", "doc_id": doc_id}

    @router.post("/{doc_id}/expand")
    async def expand_node(
        doc_id: str,
        body: dict,
        _=Depends(auth),
    ):
        """Expand a tree node by generating child nodes via LLM.

        Request body:
        - ``node_id`` (str): The node to expand.
        - ``num_children`` (int, optional): Number of children to generate
          (default 4, range 2-10).
        """
        store = _get_storage()
        if store is None:
            raise HTTPException(status_code=404, detail="Tree index not enabled")

        node_id = body.get("node_id")
        if not node_id:
            raise HTTPException(status_code=400, detail="node_id is required")

        num_children = max(2, min(10, body.get("num_children", 4)))

        tree = store.get_tree(doc_id)
        if tree is None:
            raise HTTPException(status_code=404, detail="Tree not found")

        # Access the LLM function from the RAG instance
        current = rag
        if hasattr(rag, "_current"):
            current = rag._current()

        llm_func = getattr(current, "llm_model_func", None)
        if llm_func is None:
            raise HTTPException(status_code=500, detail="LLM function not available")

        from lightrag.tree_index import expand_tree_node

        updated = await expand_tree_node(
            tree,
            node_id,
            llm_func,
            num_children=num_children,
        )
        if updated is None:
            raise HTTPException(status_code=404, detail="Node not found in tree")

        # Save the updated tree back to storage
        meta = store._meta.get(doc_id, {})
        store.save_tree(doc_id, updated, title=meta.get("title", ""))

        return updated

    return router
