"""
Tree Index storage and processing for PageIndex integration.

Stores hierarchical tree structures (mind maps) generated by PageIndex
alongside the existing knowledge graph in each workspace.

PageIndex is invoked via **MCP** (Model Context Protocol): a subprocess
running ``D:\\PageIndex-main\\mcp_server.py`` exposes the ``build_tree``
tool over stdio.  This cleanly decouples the two projects without
sys.path hacks.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from lightrag.utils import logger


class TreeIndexStorage:
    """File-based storage for page-index tree structures.

    Trees are stored per-document under ``{working_dir}/tree_index/``.

    Layout::

        {working_dir}/
            tree_index/
                tree_meta.json           # doc_id → { doc_id, title, file, timestamp }
                doc_{hash1}.json         # one tree per document
                doc_{hash2}.json
    """

    def __init__(self, working_dir: str, workspace: str = "") -> None:
        base = Path(working_dir)
        if workspace:
            base = base / workspace
        self._dir = base / "tree_index"
        self._dir.mkdir(parents=True, exist_ok=True)
        self._meta_path = self._dir / "tree_meta.json"
        self._meta: dict[str, dict[str, Any]] = {}
        self._load_meta()

    # ------------------------------------------------------------------
    # Meta helpers
    # ------------------------------------------------------------------

    def _load_meta(self) -> None:
        if self._meta_path.is_file():
            try:
                with open(self._meta_path, "r", encoding="utf-8") as f:
                    self._meta = json.load(f)
            except Exception as e:
                logger.warning("Failed to load tree meta: %s", e)
                self._meta = {}

    def _save_meta(self) -> None:
        try:
            with open(self._meta_path, "w", encoding="utf-8") as f:
                json.dump(self._meta, f, ensure_ascii=False, indent=2)
        except Exception as e:
            logger.error("Failed to save tree meta: %s", e)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def save_tree(
        self,
        doc_id: str,
        tree: dict[str, Any],
        *,
        title: str = "",
    ) -> str:
        """Save a tree structure for *doc_id*.

        Returns the filename of the saved tree.
        """
        filename = f"doc_{doc_id}.json"
        path = self._dir / filename
        with open(path, "w", encoding="utf-8") as f:
            json.dump(tree, f, ensure_ascii=False, indent=2)

        self._meta[doc_id] = {
            "doc_id": doc_id,
            "title": title or tree.get("doc_name", ""),
            "file": filename,
            "node_count": _count_nodes(tree.get("structure", [])),
        }
        self._save_meta()
        logger.info("Saved tree index for doc %s (%d nodes)", doc_id, self._meta[doc_id]["node_count"])
        return filename

    def get_tree(self, doc_id: str) -> dict[str, Any] | None:
        """Load the tree for *doc_id*, or None."""
        meta = self._meta.get(doc_id)
        if not meta:
            return None
        path = self._dir / meta["file"]
        if not path.is_file():
            return None
        try:
            with open(path, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error("Failed to load tree for %s: %s", doc_id, e)
            return None

    def delete_tree(self, doc_id: str) -> None:
        """Delete the tree for *doc_id*."""
        meta = self._meta.pop(doc_id, None)
        if meta:
            path = self._dir / meta["file"]
            if path.is_file():
                path.unlink()
            self._save_meta()
            logger.info("Deleted tree index for doc %s", doc_id)

    def list_trees(self) -> list[dict[str, Any]]:
        """List all stored trees with metadata."""
        return list(self._meta.values())

    def doc_count(self) -> int:
        return len(self._meta)


def _count_nodes(structure: list[dict]) -> int:
    """Recursively count nodes in a tree structure."""
    count = 0
    for node in structure:
        count += 1
        if "nodes" in node:
            count += _count_nodes(node["nodes"])
    return count


# ---------------------------------------------------------------------------
# PageIndex integration — via MCP (Model Context Protocol)
# ---------------------------------------------------------------------------
#
# Instead of importing pageindex directly (which required sys.path hacks),
# we launch an MCP server subprocess (D:\PageIndex-main\mcp_server.py) and
# call the ``build_tree`` tool over stdio.  This cleanly decouples the two
# projects and allows any MCP host to reuse the same tools.
# ---------------------------------------------------------------------------


def _resolve_mcp_server_path() -> str:
    """Locate ``mcp_server.py`` on disk."""
    here = Path(__file__).resolve().parent
    candidates = [
        here.parent.parent / "PageIndex-main" / "mcp_server.py",
        here.parent.parent.parent / "PageIndex-main" / "mcp_server.py",
        Path("D:/PageIndex-main/mcp_server.py"),
    ]
    for p in candidates:
        if p.is_file():
            return str(p)
    return "mcp_server.py"


def _resolve_file_path(file_path: str) -> str:
    """Resolve a possibly-relative file path by searching common locations."""
    if os.path.isfile(file_path):
        return file_path
    cwd = os.getcwd()
    for candidate in [
        os.path.join(cwd, file_path),
        os.path.join(cwd, "inputs", file_path),
        os.path.join(cwd, "inputs", "__parsed__", file_path),
        os.path.join(cwd, "rag_storage", file_path),
    ]:
        if os.path.isfile(candidate):
            logger.info("PageIndex: resolved %s -> %s", file_path, candidate)
            return candidate
    return file_path


# ---- Subprocess bridge to PageIndex --------------------------------------
#
# Instead of importing pageindex directly (which required sys.path hacks) or
# using the MCP SDK client (which has async/lifecycle issues in the LightRAG
# pipeline), we spawn a one-shot subprocess that runs
# ``D:\PageIndex-main\call_tree.py`` and captures its JSON output.
#
# The ``mcp_server.py`` is still available at D:\PageIndex-main\mcp_server.py
# as a standalone MCP server for external tools (Claude Desktop, Copilot, etc).
# ---------------------------------------------------------------------------


import subprocess


def _resolve_call_tree_script() -> str:
    """Locate ``call_tree.py`` on disk."""
    here = Path(__file__).resolve().parent
    candidates = [
        here.parent.parent / "PageIndex-main" / "call_tree.py",
        here.parent.parent.parent / "PageIndex-main" / "call_tree.py",
        Path("D:/PageIndex-main/call_tree.py"),
    ]
    for p in candidates:
        if p.is_file():
            return str(p)
    return str(Path("D:/PageIndex-main/call_tree.py"))


def _call_pageindex(file_path: str, model: str | None = None) -> dict | None:
    """Run ``call_tree.py`` as a subprocess and return the parsed tree dict."""
    script = _resolve_call_tree_script()
    args = [sys.executable, script, file_path, "temp"]
    if model:
        args.append(model)

    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=600,  # 10 min max for LLM calls
        )
    except subprocess.TimeoutExpired:
        logger.error("PageIndex subprocess timed out for %s", file_path)
        return None
    except Exception as exc:
        logger.error("PageIndex subprocess failed: %s", exc)
        return None

    if result.returncode != 0:
        logger.error(
            "PageIndex subprocess exited %d: %s",
            result.returncode,
            result.stderr[:500],
        )
        return None

    # stderr may contain progress messages; stdout has the JSON result
    # The last line of stdout is the JSON payload
    lines = result.stdout.strip().split("\n")
    # Find the last line that starts with {
    json_line = ""
    for line in reversed(lines):
        line = line.strip()
        if line.startswith("{"):
            json_line = line
            break

    if not json_line:
        logger.error("PageIndex subprocess: no JSON found in output")
        return None

    try:
        tree = json.loads(json_line)
    except json.JSONDecodeError as exc:
        logger.error("PageIndex subprocess: invalid JSON: %s", exc)
        return None

    if tree.get("error"):
        logger.error("PageIndex subprocess error: %s", tree["error"])
        return None

    return tree


# ---------------------------------------------------------------------------
# Public builder functions (unchanged signatures)
# ---------------------------------------------------------------------------


def build_tree_from_text(
    text: str,
    doc_id: str,
    *,
    doc_name: str = "",
    model: str | None = None,
    add_summary: bool = True,
    add_text: bool = True,
) -> dict | None:
    """Convert parsed text content into a hierarchical tree.

    Parses Markdown-style headings (``#`` … ``######``) to create nested
    ``structure`` nodes.  Text between headings is attached as the
    parent node's ``text`` content.  If no headings are found, falls
    back to a single root node containing all text.

    Lightweight fallback when the PageIndex MCP server is unavailable.
    """
    import re

    lines = text.split("\n")
    # Detect heading lines: lines starting with # … ######
    heading_re = re.compile(r"^(#{1,6})\s+(.+)$")

    # ── Parse headings into a flat list ──────────────────────────────
    parsed: list[tuple[int, str, str]] = []  # (level, title, body_text)
    current_level = 0
    current_title = ""
    current_body: list[str] = []

    def flush_section() -> None:
        nonlocal current_level, current_title, current_body
        if current_level > 0:
            parsed.append(
                (current_level, current_title, "\n".join(current_body).strip())
            )
        current_level = 0
        current_title = ""
        current_body = []

    # Capture text before the first heading as a level-0 "preamble"
    preamble: list[str] = []

    for line in lines:
        m = heading_re.match(line)
        if m:
            flush_section()
            level = len(m.group(1))
            current_level = level
            current_title = m.group(2).strip()
            current_body = []
        elif current_level > 0:
            current_body.append(line)
        else:
            preamble.append(line)

    flush_section()

    doc_title = doc_name or doc_id

    node_counter = [0]

    # ── Fallback: no headings → split by paragraphs ──────────────
    if not parsed:
        paragraphs = _split_into_paragraphs(text)
        if len(paragraphs) > 1:
            # Check if paragraphs have depth info (int first element)
            if isinstance(paragraphs[0], tuple) and isinstance(paragraphs[0][0], int):
                # Hierarchical paragraphs with depth
                root_node = _make_node(doc_title, "", node_counter, add_text)
                para_stack: list[tuple[int, dict]] = [(0, root_node)]
                for depth, para_title, para_body in paragraphs:
                    child = _make_node(para_title, para_body, node_counter, add_text)
                    while para_stack and para_stack[-1][0] >= depth:
                        para_stack.pop()
                    if para_stack:
                        para_stack[-1][1]["nodes"].append(child)
                    else:
                        root_node["nodes"].append(child)
                    para_stack.append((depth, child))
            else:
                # Flat paragraphs (old format, str title)
                root_node = _make_node(doc_title, "", node_counter, add_text)
                for para_title, para_body in paragraphs:
                    child = _make_node(para_title, para_body, node_counter, add_text)
                    root_node["nodes"].append(child)
            return {
                "doc_name": doc_title,
                "doc_id": doc_id,
                "structure": [root_node],
            }
        # Single paragraph → flat root node
        root_node = _make_node(doc_title, text, node_counter, add_text)
        return {
            "doc_name": doc_title,
            "doc_id": doc_id,
            "structure": [root_node],
        }

    # ── Build tree nodes from parsed headings ────────────────────
    root_stack: list[dict] = []

    # If the first heading is level 1, use it as root
    preamble_text = "\n".join(preamble).strip()
    if parsed[0][0] == 1:
        first_level, first_title, first_body = parsed.pop(0)
        root_node = _make_node(first_title, first_body, node_counter, add_text)
        root_stack.append((1, root_node))
    else:
        root_node = _make_node(doc_title, preamble_text, node_counter, add_text)
        root_stack.append((0, root_node))

    for level, title, body in parsed:
        child = _make_node(title, body, node_counter, add_text)
        while root_stack and root_stack[-1][0] >= level:
            root_stack.pop()
        if root_stack:
            root_stack[-1][1]["nodes"].append(child)
        else:
            root_node["nodes"].append(child)
        root_stack.append((level, child))

    return {
        "doc_name": doc_title,
        "doc_id": doc_id,
        "structure": [root_node],
    }


def is_flat_tree(tree: dict | None) -> bool:
    """Return ``True`` if the tree has no meaningful hierarchy.

    A tree is "flat" when the total node count is ≤ 2 (root + at most
    one child), meaning there is no real nesting or multi-section
    structure.
    """
    if tree is None:
        return True
    struct = tree.get("structure", [])
    if not struct:
        return True
    total = _count_nodes(struct)
    return total <= 2


async def build_tree_from_text_with_llm(
    text: str,
    doc_id: str,
    llm_func: object,
    *,
    doc_name: str = "",
) -> dict | None:
    """Build a hierarchical tree via LLM extraction (提纲格式).

    Sends the document text to the LLM with a prompt requesting a numbered
    outline suitable for mind maps.  The LLM response is parsed into a
    ``TreeStructure`` dict.
    """
    import re as _re

    SYSTEM_PROMPT = "你是一个文档结构分析专家。请根据用户提供的长文本内容生成适合思维导图的中文提纲。"

    max_chars = 6000
    truncated = text[:max_chars]
    if len(text) > max_chars:
        truncated += "\n\n[... 文档过长已截断，基于可见结构生成提纲 ...]"

    MAX_DEPTH = 3
    MAX_CHILDREN = 8
    title = doc_name or doc_id

    USER_PROMPT = f"""请根据以下长文本内容，生成适合思维导图使用的中文提纲。

输出要求：
1. 最多 {MAX_DEPTH} 层。
2. 每个节点标题尽量简短。
3. 只输出提纲正文，不要输出解释、说明、前言或总结。
4. 每行只写一个节点。
5. 一级节点使用格式：1. 标题
6. 二级节点使用格式：1.1 标题
7. 三级节点使用格式：1.1.1 标题
8. 不要使用"一、二、三"这种格式。
9. 不要输出 markdown 符号、项目符号或多余空行。
10. 子节点数量尽量不要超过 {MAX_CHILDREN}。

文档标题：
{title}

文档内容：
```
{truncated}
```"""

    try:
        response = await llm_func(USER_PROMPT, system_prompt=SYSTEM_PROMPT)

        if not response or not isinstance(response, str):
            logger.warning("LLM tree building returned empty response")
            return build_tree_from_text(text, doc_id, doc_name=doc_name)

        # ── 将提纲文本解析为 TreeStructure dict ──────────────
        lines = response.strip().split("\n")
        # 去掉可能的空行首尾
        lines = [ln.strip() for ln in lines if ln.strip()]

        # 匹配提纲行：如 "1. 标题", "1.1 标题", "1.2.3 标题"
        outline_re = _re.compile(r"^(\d+(?:\.\d+)*)[.．\s]+(.+)$")

        structure = []
        node_counter = [0]

        def _make_tree_node(
            outline_path: str, node_title: str, children: list
        ) -> dict:
            nonlocal node_counter
            node_counter[0] += 1
            return {
                "title": node_title.strip(),
                "node_id": f"{node_counter[0]:04d}",
                "summary": "",
                "text": "",
                "nodes": children,
            }

        # 用栈来构建层级
        # stack 中每个元素为 (level, node_dict)
        stack: list[tuple[int, dict]] = []

        for line in lines:
            m = outline_re.match(line)
            if not m:
                continue  # 跳过不符合格式的行
            num_str = m.group(1)  # "1" / "1.1" / "1.2.3"
            node_title = m.group(2).strip()
            # 计算层级（按小数点数）
            level = num_str.count(".") + 1

            if level > MAX_DEPTH:
                continue

            node = _make_tree_node(num_str, node_title, [])

            if level == 1:
                # 一级节点：直接加入 structure
                structure.append(node)
                stack = [(1, node)]
            else:
                # 找父节点
                while stack and stack[-1][0] >= level:
                    stack.pop()
                if stack:
                    parent = stack[-1][1]
                    parent["nodes"].append(node)
                else:
                    # 没有父节点，降级为一级
                    structure.append(node)
                    stack = [(1, node)]
                    continue
                stack.append((level, node))

        if not structure:
            logger.warning("LLM outline parsing produced no nodes, falling back")
            return build_tree_from_text(text, doc_id, doc_name=doc_name)

        # 统计节点总数做合理性检查
        total = _count_nodes(structure)
        if total < 1 or total > 100:
            logger.warning(
                "LLM tree building produced %d nodes (unreasonable), falling back",
                total,
            )
            return build_tree_from_text(text, doc_id, doc_name=doc_name)

        tree = {
            "doc_name": doc_name or doc_id,
            "doc_id": doc_id,
            "structure": structure,
        }

        logger.info("LLM outline parsing produced %d nodes for %s", total, doc_id)
        return tree

    except Exception as exc:
        logger.warning("LLM tree building failed: %s, falling back to heuristic", exc)
        return build_tree_from_text(text, doc_id, doc_name=doc_name)


def _make_node(
    title: str,
    body: str,
    counter: list[int],
    add_text: bool,
) -> dict:
    """Create a single tree node dict."""
    counter[0] += 1
    return {
        "title": title,
        "node_id": f"{counter[0]:04d}",
        "summary": body[:500] if body else "",
        "text": body if add_text else "",
        "nodes": [],
    }


def _split_into_paragraphs(text: str) -> list[tuple[str, str]]:
    """Split plain text into (title, content) pairs.

    Strategy:
    1. Split by blank lines into paragraph blocks.
    2. Check each block for a real section heading pattern at its start.
    3. If heading found → use it as section title; remaining block lines = body.
    4. If no real heading found → treat whole block as one paragraph body
       (title becomes "段落 N").
    5. Use numbered patterns (2.1, 2.2.1, 1., 一、) to determine depth.

    Returns ``list[tuple[depth, title, body]]`` when headings detected,
    otherwise ``list[tuple[str, str]]`` (flat paragraphs).
    """
    import re

    blocks = re.split(r"\n\s*\n", text.strip())
    blocks = [b.strip() for b in blocks if b.strip()]
    if not blocks:
        return []

    # ── Detect a REAL section heading at the start of a block ──────────
    # Returns (depth, title) or None.  Only inspects the FIRST LINE of
    # the block — remaining lines become body text.
    def detect_section_header(block: str) -> tuple[int, str] | None:
        first_line = block.strip().split("\n")[0].strip()
        if not first_line:
            return None
        # Skip figure/table captions and garbled text
        if first_line.startswith("图") or first_line.startswith("表"):
            return None
        if len(first_line) < 4:
            return None

        # 2.1 / 2.2.1 style decimal numbering
        m = re.match(r"^(\d+(?:\.\d+)+)\s+(.+)$", first_line)
        if m:
            parts = m.group(1).split(".")
            title = m.group(2).strip()
            if len(title) >= 2:
                return (len(parts), title)

        # Single digit followed by text: "2 实验目的"
        m = re.match(r"^(\d+)\s+(.+)$", first_line)
        if m:
            title = m.group(2).strip()
            if len(title) >= 3:
                return (2, title)

        # Chinese numbering: 一、 二、 (一) （一）
        m = re.match(r"^[（(]?[一二三四五六七八九十百]+[）)\).、]\s*(.+)$", first_line)
        if m and len(m.group(1)) >= 2:
            return (2, first_line)

        # Numbered item: "1．说明" (only short section-like text)
        m = re.match(r"^(\d+)．(.+)$", first_line)
        if m:
            title = m.group(2).strip()
            # Short title → section heading; long title → list item content
            if 2 <= len(title) <= 8:
                return (2, first_line)

        # Experiment/lab heading: "实验1 DBMS建库", "实验一 数据库"
        m = re.match(r"^实验[一二三四五六七八九十\d]\s+(.+)$", first_line)
        if m and len(m.group(1).strip()) >= 2:
            return (2, first_line)

        return None

    # ── Classify blocks ─────────────────────────────────────────────────
    # Try to detect section headers across ALL blocks first.
    # If at least 2 blocks have real section headers, use hierarchical mode.
    classified: list[tuple[int | None, str, str]] = []  # (depth or None, title, body)
    for block in blocks:
        h = detect_section_header(block)
        if h is not None:
            depth, title = h
            # body is everything after the first line
            lines = block.split("\n")
            body = "\n".join(lines[1:]).strip()
            classified.append((depth, title, body))
        else:
            classified.append((None, block, ""))

    # Count real section headers
    heading_count = sum(1 for c in classified if c[0] is not None)

    # ── Quality gate: only use hierarchy if we have ≥2 real headings ──
    # AND they represent a meaningful fraction of total blocks.
    # For fragmented content (many small figure-blocks), fall back to flat.
    USE_HIERARCHY = heading_count >= 2 and heading_count >= max(2, len(blocks) * 0.08)

    if USE_HIERARCHY:
        pairs: list[tuple[int, str, str]] = []
        # First block: if it has no heading depth, use first line as preamble
        if classified[0][0] is None:
            first_text = classified[0][1]
            first_lines = first_text.split("\n")
            pairs.append((1, first_lines[0].strip()[:60], first_text))
        elif classified[0][0] == 1:
            pairs.append((classified[0][0], classified[0][1], classified[0][2]))
        else:
            pairs.append((classified[0][0], classified[0][1], classified[0][2]))

        for depth, title, body in classified[1:]:
            if depth is not None:
                pairs.append((depth, title, body))
            else:
                # Non-heading block → attach as content of last heading
                if pairs:
                    last_depth, last_title, last_body = pairs.pop()
                    new_body = (last_body + "\n\n" + title) if last_body else title
                    pairs.append((last_depth, last_title, new_body))
                else:
                    pairs.append((1, title[:60], title))

        return pairs

    # ── No real headings → flat paragraph list ─────────────────────────
    result: list[tuple[str, str]] = []
    for b in blocks:
        blines = b.split("\n")
        first = blines[0].strip()
        if len(first) < 50 and len(blines) > 1:
            result.append((first, "\n".join(blines[1:]).strip()))
        else:
            result.append((f"段落 {len(result) + 1}", b))
    return result


def build_pageindex_tree(
    file_path: str,
    doc_id: str,
    *,
    model: str | None = None,
) -> dict | None:
    """Build a hierarchical tree via the PageIndex subprocess.

    Spawns ``call_tree.py`` (from ``D:\\PageIndex-main``) as a one-shot
    subprocess and parses the JSON tree from its stdout.

    For unsupported formats (or if the subprocess fails), attempts a
    plain-text fallback by reading the file.  The caller (``_build_pageindex_tree``
    in ``lightrag.py``) additionally falls back to the in-memory text content
    from ``full_docs`` if everything else fails.
    """
    suffix = Path(file_path).suffix.lower()

    # ── PDF / MD / Markdown → full PageIndex ──────────────────────────
    if suffix in (".pdf", ".md", ".markdown"):
        try:
            tree = _call_pageindex(file_path, model=model)
            if tree:
                tree["doc_id"] = doc_id
                return tree
        except Exception as e:
            logger.warning("PageIndex subprocess failed for %s: %s", file_path, e)

    # ── Plain-text fallback: read file and build flat tree ────────────
    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as f:
            text = f.read()
    except Exception:
        # Binary file or missing file — caller will use text_content fallback
        return None

    if not text.strip():
        return None
    return build_tree_from_text(text, doc_id, doc_name=Path(file_path).stem)


# ---------------------------------------------------------------------------
# Interactive tree expansion — LLM-driven child node generation
# ---------------------------------------------------------------------------


def _find_node_by_id(
    structure: list[dict], node_id: str
) -> dict | None:
    """Recursively search the tree structure for a node with the given *node_id*."""
    for node in structure:
        if node.get("node_id") == node_id:
            return node
        if "nodes" in node:
            found = _find_node_by_id(node["nodes"], node_id)
            if found is not None:
                return found
    return None


def _find_parent_by_id(
    structure: list[dict], node_id: str
) -> dict | None:
    """Find the parent dict whose ``nodes`` list contains the target *node_id*."""
    for node in structure:
        children = node.get("nodes", [])
        for child in children:
            if child.get("node_id") == node_id:
                return node
            if "nodes" in child:
                found = _find_parent_by_id(child["nodes"], node_id)
                if found is not None:
                    return found
    return None


async def expand_tree_node(
    tree: dict,
    node_id: str,
    llm_func: object,
    *,
    num_children: int = 4,
    add_text: bool = True,
) -> dict | None:
    """Use LLM to generate child nodes for the given *node_id* in *tree*.

    The LLM receives the parent node's title and summary and returns a list
    of subtopics.  New child nodes are **appended** to any existing children.

    Returns the updated tree dict, or ``None`` if the node was not found.
    """
    structure = tree.get("structure", [])
    parent = _find_node_by_id(structure, node_id)
    if parent is None:
        logger.warning("expand_tree_node: node %s not found in tree", node_id)
        return None

    parent_title = parent.get("title", "")
    parent_summary = parent.get("summary", "") or parent.get("prefix_summary", "")
    parent_text = parent.get("text", "")

    # ── Build LLM prompt ──────────────────────────────────────────────
    SYSTEM_PROMPT = (
        "你是一个知识结构化专家。请根据给定的主题，生成合理的子主题列表，"
        "用于构建思维导图。每个子主题应该与父主题紧密相关，覆盖其重要方面。"
    )

    context = f"父节点标题：{parent_title}\n"
    if parent_summary:
        context += f"父节点摘要：{parent_summary[:300]}\n"
    if parent_text:
        context += f"父节点内容：{parent_text[:500]}\n"

    USER_PROMPT = f"""请根据以下父节点主题，生成 {num_children} 个合理的子节点。

{context}
输出要求：
1. 每行输出一个子节点，格式为："子节点标题 | 简短描述"
2. 标题尽量简短（不超过 20 字），描述不超过 50 字
3. 子节点应覆盖父主题的不同方面或子组成部分
4. 只输出子节点列表，不要输出解释、说明或总结
5. 不要输出 markdown 符号或多余空行

示例：
数据结构 | 数据的逻辑组织形式
算法分析 | 评估算法效率的方法
"""

    try:
        # llm_func is an async callable that accepts (prompt, system_prompt=...)
        response = await llm_func(USER_PROMPT, system_prompt=SYSTEM_PROMPT)
        if not response or not isinstance(response, str):
            logger.warning("expand_tree_node: LLM returned empty response")
            return tree

        # ── Parse LLM response into child nodes ───────────────────────
        lines = [ln.strip() for ln in response.strip().split("\n") if ln.strip()]
        import re

        new_nodes: list[dict] = []
        node_counter = [0]

        # Count existing nodes in the whole tree to continue numbering
        def count_all(structure: list[dict]) -> int:
            total = 0
            for n in structure:
                total += 1
                if "nodes" in n:
                    total += count_all(n["nodes"])
            return total

        start_count = count_all(structure)

        # Also count existing children so numbering is correct
        existing_count = len(parent.get("nodes", []))

        for line in lines:
            # Remove leading numbering like "1." or "1、" or "- " or "* "
            line = re.sub(r"^[\d]+[.．、\)\s]\s*", "", line).strip()
            line = re.sub(r"^[-*•]\s*", "", line).strip()

            # Split by "|" or "：" or ": " or "--"
            parts = re.split(r"\s*[|：:]\s*", line, maxsplit=1)
            title = parts[0].strip()
            desc = parts[1].strip() if len(parts) > 1 else ""

            if not title:
                continue

            # Generate node_id
            next_id = start_count + len(new_nodes) + 1
            node = {
                "title": title,
                "node_id": f"{next_id:04d}",
                "summary": desc[:500] if desc else "",
                "text": desc if add_text else "",
                "nodes": [],
            }
            new_nodes.append(node)

        if not new_nodes:
            logger.warning("expand_tree_node: no valid child nodes parsed from LLM response")
            return tree

        # ── Append new nodes to parent's children ──────────────────────
        if "nodes" not in parent:
            parent["nodes"] = []
        parent["nodes"].extend(new_nodes)

        logger.info(
            "expand_tree_node: added %d children to node %s (%s)",
            len(new_nodes),
            node_id,
            parent_title,
        )
        return tree

    except Exception as exc:
        logger.error("expand_tree_node failed: %s", exc)
        return tree
